[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "faker>=40.37.0",
    "fastapi[standard]>=0.138.2",
    "passlib[argon2]>=1.7.4",
    "psycopg>=3.3.4",
    "psycopg2>=2.9.12",
    "pydantic-settings>=2.14.2",
    "python-jose[cryptography]>=3.5.0",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.51",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
 