"""Add `phone_number` Column For `Users` Table

Revision ID: dd71d4f92157
Revises: 5fdc0b94c779
Create Date: 2026-09-03 21:38:15.366093

"""
from markdown_it.rules_block import table
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd71d4f92157'
down_revision: Union[str, Sequence[str], None] = '5fdc0b94c779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_number', table_name='users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
